blank_issues_enabled: true
contact_links:
  - name: General Discussion
    url: https://github.com/scovetta/oss-supply-chain/discussions
    about: For questions or discussions that aren't bug reports or feature requests
